// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqS0Yrvl-lL5XbhtqBc2XOooTJgxeqStA',
    appId: '1:988029147686:web:84fd45028024352083a4e7',
    messagingSenderId: '988029147686',
    projectId: 'rd-music-player',
    authDomain: 'rd-music-player.firebaseapp.com',
    storageBucket: 'rd-music-player.firebasestorage.app',
    measurementId: 'G-RFR1PZFBEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6IWz8xZRDrRWOY8Q9Zda_QIzJvq8wUq0',
    appId: '1:988029147686:android:19f0f9f12bd7862983a4e7',
    messagingSenderId: '988029147686',
    projectId: 'rd-music-player',
    storageBucket: 'rd-music-player.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00XWAB5uzAFJ-uSGnUPLIPKNCrtC6X5k',
    appId: '1:988029147686:ios:dfe929d69cde1f0483a4e7',
    messagingSenderId: '988029147686',
    projectId: 'rd-music-player',
    storageBucket: 'rd-music-player.firebasestorage.app',
    iosBundleId: 'com.spotify.web.spotifyWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00XWAB5uzAFJ-uSGnUPLIPKNCrtC6X5k',
    appId: '1:988029147686:ios:dfe929d69cde1f0483a4e7',
    messagingSenderId: '988029147686',
    projectId: 'rd-music-player',
    storageBucket: 'rd-music-player.firebasestorage.app',
    iosBundleId: 'com.spotify.web.spotifyWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqS0Yrvl-lL5XbhtqBc2XOooTJgxeqStA',
    appId: '1:988029147686:web:f26c8d18a583957383a4e7',
    messagingSenderId: '988029147686',
    projectId: 'rd-music-player',
    authDomain: 'rd-music-player.firebaseapp.com',
    storageBucket: 'rd-music-player.firebasestorage.app',
    measurementId: 'G-1ENBKYQQGE',
  );
}
